version: '3.4'

services:
  trucksapi:
    depends_on: 
        - db
    image: ${DOCKER_REGISTRY-}trucksapi
    build:
      context: ./src
      dockerfile: TrucksApi/Dockerfile
  db:
    
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
     - ACCEPT_EULA=Y
     - MSSQL_SA_PASSWORD=yourStrong(!)Password
    ports:
        - "1433:1433"
